name: e3py310
channels:
  - nvidia
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - binutils_impl_linux-64=2.40=h5293946_0
  - binutils_linux-64=2.40.0=hc2dff05_2
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - cuda=12.9.1=0
  - cuda-cccl_linux-64=12.9.27=0
  - cuda-command-line-tools=12.9.1=0
  - cuda-compiler=12.9.1=0
  - cuda-crt-dev_linux-64=12.9.86=0
  - cuda-crt-tools=12.9.86=0
  - cuda-cudart=12.9.79=0
  - cuda-cudart-dev=12.9.79=0
  - cuda-cudart-dev_linux-64=12.9.79=0
  - cuda-cudart-static=12.9.79=0
  - cuda-cudart-static_linux-64=12.9.79=0
  - cuda-cudart_linux-64=12.9.79=0
  - cuda-cuobjdump=12.9.82=1
  - cuda-cupti=12.9.79=0
  - cuda-cupti-dev=12.9.79=0
  - cuda-cuxxfilt=12.9.82=1
  - cuda-driver-dev=12.9.79=0
  - cuda-driver-dev_linux-64=12.9.79=0
  - cuda-gdb=12.9.79=1
  - cuda-libraries=12.9.1=0
  - cuda-libraries-dev=12.9.1=0
  - cuda-nsight=12.9.79=0
  - cuda-nvcc=12.9.86=0
  - cuda-nvcc-dev_linux-64=12.9.86=0
  - cuda-nvcc-impl=12.9.86=0
  - cuda-nvcc-tools=12.9.86=0
  - cuda-nvcc_linux-64=12.9.86=0
  - cuda-nvdisasm=12.9.88=1
  - cuda-nvml-dev=12.9.79=1
  - cuda-nvprof=12.9.79=0
  - cuda-nvprune=12.9.82=1
  - cuda-nvrtc=12.9.86=0
  - cuda-nvrtc-dev=12.9.86=0
  - cuda-nvtx=12.9.79=0
  - cuda-nvvm-dev_linux-64=12.9.86=0
  - cuda-nvvm-impl=12.9.86=0
  - cuda-nvvm-tools=12.9.86=0
  - cuda-nvvp=12.9.79=1
  - cuda-opencl=12.9.19=0
  - cuda-opencl-dev=12.9.19=0
  - cuda-profiler-api=12.9.79=0
  - cuda-runtime=12.9.1=0
  - cuda-sanitizer-api=12.9.79=1
  - cuda-toolkit=12.9.1=0
  - cuda-tools=12.9.1=0
  - cuda-version=12.9=3
  - cuda-visual-tools=12.9.1=0
  - dbus=1.16.2=h5bd4931_0
  - expat=2.7.1=h6a678d5_0
  - fontconfig=2.14.1=h55d465d_3
  - freetype=2.13.3=h4a9f257_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_2
  - gds-tools=1.14.1.1=4
  - gmp=6.3.0=h6a678d5_0
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_2
  - icu=73.1=h6a678d5_0
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - ld_impl_linux-64=2.40=h12ee557_0
  - libcublas=12.9.1.4=0
  - libcublas-dev=12.9.1.4=0
  - libcufft=11.4.1.4=0
  - libcufft-dev=11.4.1.4=0
  - libcufile=1.14.1.1=4
  - libcufile-dev=1.14.1.1=4
  - libcurand=10.3.10.19=0
  - libcurand-dev=10.3.10.19=0
  - libcusolver=11.7.5.82=0
  - libcusolver-dev=11.7.5.82=0
  - libcusparse=12.5.10.65=0
  - libcusparse-dev=12.5.10.65=0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=11.2.0=h1234567_1
  - libglib=2.84.2=h37c7471_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libnpp=12.4.1.87=0
  - libnpp-dev=12.4.1.87=0
  - libnvfatbin=12.9.82=0
  - libnvfatbin-dev=12.9.82=0
  - libnvjitlink=12.9.86=0
  - libnvjitlink-dev=12.9.86=0
  - libnvjpeg=12.4.0.76=0
  - libnvjpeg-dev=12.4.0.76=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.8=hfdd30dd_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - nsight-compute=2025.2.1.3=0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openssl=3.0.17=h5eee18b_0
  - pcre2=10.42=hebb0a14_1
  - pip=25.2=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=h1a3bd86_0
  - readline=8.3=hc2a1206_0
  - sqlite=3.50.2=hb25bd0a_1
  - sysroot_linux-64=2.17=h57e8cba_10
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.10.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiohttp-cors==0.8.1
      - aiosignal==1.4.0
      - airportsdata==20250909
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.10.0
      - astor==0.8.1
      - async-timeout==5.0.1
      - attrs==25.3.0
      - blake3==1.0.5
      - cachetools==5.5.2
      - certifi==2025.8.3
      - cfgv==3.4.0
      - charset-normalizer==3.4.3
      - click==8.2.1
      - cloudpickle==3.1.1
      - codetiming==1.4.0
      - colorful==0.5.7
      - compressed-tensors==0.9.3
      - cupy-cuda12x==13.6.0
      - datasets==4.0.0
      - deprecated==1.2.18
      - depyf==0.18.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distlib==0.4.0
      - distro==1.9.0
      - dnspython==2.8.0
      - einops==0.8.1
      - email-validator==2.3.0
      - exceptiongroup==1.3.0
      - fastapi==0.116.1
      - fastapi-cli==0.0.11
      - fastapi-cloud-cli==0.1.5
      - fastrlock==0.8.3
      - filelock==3.19.1
      - flash-attn==2.6.1
      - frozenlist==1.7.0
      - fsspec==2025.9.0
      - gguf==0.17.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-api-core==2.25.1
      - google-auth==2.40.3
      - googleapis-common-protos==1.70.0
      - grpcio==1.74.0
      - h11==0.16.0
      - hf-xet==1.1.9
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.34.4
      - hydra-core==1.3.2
      - identify==2.6.14
      - idna==3.10
      - importlib-metadata==8.0.0
      - interegular==0.3.3
      - jinja2==3.1.6
      - jiter==0.10.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - lark==1.2.2
      - latex2sympy2-extended==1.10.2
      - liger-kernel==0.6.2
      - llguidance==0.7.30
      - llvmlite==0.44.0
      - lm-format-enforcer==0.10.12
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - math-verify==0.8.0
      - mdurl==0.1.2
      - mistral-common==1.8.4
      - mpmath==1.3.0
      - msgpack==1.1.1
      - msgspec==0.19.0
      - multidict==6.6.4
      - multiprocess==0.70.16
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - ninja==1.13.0
      - nodeenv==1.9.1
      - numba==0.61.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - openai==1.107.1
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opencv-python-headless==4.12.0.88
      - opentelemetry-api==1.26.0
      - opentelemetry-exporter-otlp==1.26.0
      - opentelemetry-exporter-otlp-proto-common==1.26.0
      - opentelemetry-exporter-otlp-proto-grpc==1.26.0
      - opentelemetry-exporter-otlp-proto-http==1.26.0
      - opentelemetry-exporter-prometheus==0.58b0
      - opentelemetry-proto==1.26.0
      - opentelemetry-sdk==1.26.0
      - opentelemetry-semantic-conventions==0.47b0
      - opentelemetry-semantic-conventions-ai==0.4.13
      - orjson==3.11.3
      - outlines==0.1.11
      - outlines-core==0.1.26
      - packaging==25.0
      - pandas==2.3.2
      - partial-json-parser==0.2.1.1.post6
      - peft==0.17.1
      - pillow==11.3.0
      - platformdirs==4.4.0
      - pre-commit==4.3.0
      - prometheus-client==0.22.1
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.3.2
      - proto-plus==1.26.1
      - protobuf==4.25.8
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - py-spy==0.4.1
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybind11==3.0.1
      - pycountry==24.6.1
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydantic-extra-types==2.10.5
      - pygments==2.19.2
      - pylatexenc==2.10
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - python-json-logger==3.3.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyvers==0.1.0
      - pyyaml==6.0.2
      - pyzmq==27.1.0
      - ray==2.49.1
      - referencing==0.36.2
      - regex==2025.9.1
      - requests==2.32.5
      - rich==14.1.0
      - rich-toolkit==0.15.1
      - rignore==0.6.4
      - rpds-py==0.27.1
      - rsa==4.9.1
      - safetensors==0.6.2
      - scipy==1.15.3
      - sentencepiece==0.2.1
      - sentry-sdk==2.37.1
      - setuptools==80.9.0
      - shellingham==1.5.4
      - six==1.17.0
      - smart-open==7.3.1
      - smmap==5.0.2
      - sniffio==1.3.1
      - starlette==0.47.3
      - sympy==1.13.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensordict==0.6.2
      - tiktoken==0.11.0
      - tokenizers==0.22.0
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchdata==0.11.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - transformers==4.56.1
      - triton==3.2.0
      - typer==0.17.4
      - typing-extensions==4.15.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.35.0
      - uvloop==0.21.0
      - verl==0.3.1.dev0
      - virtualenv==20.34.0
      - vllm==0.8.5.post1
      - wandb==0.21.3
      - watchfiles==1.1.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wrapt==1.17.3
      - xformers==0.0.29.post2
      - xgrammar==0.1.18
      - xxhash==3.5.0
      - yarl==1.20.1
      - zipp==3.23.0
prefix: /home/anamika/miniconda3/envs/e3py310
